# Generated by Django 5.1.2 on 2025-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('defaulter', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Borrower',
            },
        ),
    ]
