# Generated by Django 5.1.2 on 2025-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0002_plots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='plot',
            field=models.ImageField(upload_to='plots/'),
        ),
    ]
