# Generated by Django 5.1.2 on 2025-07-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0003_alter_plots_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterModelTable(
            name='plots',
            table='Plots',
        ),
    ]
